// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB61ZKL6y4D-N0NOoFEcwlMt2obPoP-C10',
    appId: '1:26664515281:web:dab1f183dae981da6377f0',
    messagingSenderId: '26664515281',
    projectId: 'crictrax-d9945',
    authDomain: 'crictrax-d9945.firebaseapp.com',
    storageBucket: 'crictrax-d9945.firebasestorage.app',
    measurementId: 'G-DP2VD4R9YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6XIpLBxEPixggsWq8yxJu7RmNUf-_LOw',
    appId: '1:26664515281:android:bdbb426afe67a95f6377f0',
    messagingSenderId: '26664515281',
    projectId: 'crictrax-d9945',
    storageBucket: 'crictrax-d9945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx9I_zdQCuj4y6bH2RlnTPHOUWPNEgtmo',
    appId: '1:26664515281:ios:1523f0bd92b0f2d06377f0',
    messagingSenderId: '26664515281',
    projectId: 'crictrax-d9945',
    storageBucket: 'crictrax-d9945.firebasestorage.app',
    androidClientId: '26664515281-1l5m7bqkg7sqobto7qdgbo1ud9g5kcdi.apps.googleusercontent.com',
    iosClientId: '26664515281-eapq0j38p9crdn2ak7nolh2hdkrt6171.apps.googleusercontent.com',
    iosBundleId: 'com.example.crictrax',
  );
}
